backend:
  name: github
site_url: localhost:8000/blog # Domain alınınca domaine değiştirilecek
display_url: localhost:8000/blog # Domain alınınca domaine değiştirilecek
local_backend: true
media_folder: static/img  
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'blog'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
locale: 'tr'